name: Generate Checksums

on:
  release:
    types: [published]

jobs:
  generate-checksums:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Checksums
        run: |
          mkdir -p checksums
          RELEASE_DIR=release
          if [ -d "$RELEASE_DIR" ] && [ "$(ls -A $RELEASE_DIR)" ]; then
            for asset in $RELEASE_DIR/*.zip $RELEASE_DIR/*.js; do
              sha256sum $asset >> checksums/checksums.txt
            done
          else
            echo "No files found in release directory"
            exit 1
          fi

      - name: Upload Checksums
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: checksums/checksums.txt
          asset_name: checksums.txt
          asset_content_type: text/plain
